### ISSUE TITLE
执行收集类别的时候出现了这个问题

### ISSUE THREAD

**Issue by IDONKN** [QuantumLiu/PornSpider#4]
TypeError: can only concatenate tuple (not "NoneType") to tuple

**Comment by IDONKN** [comment]
Traceback (most recent call last):
  File "collect_category.py", line 20, in <module>
    pornhub.init_category(name_list=name_list)
  File "H:\python\PornSpider-master\pornspider.py", line 32, in init_category
    clist=init_categories_p(self.category_params,(name_list if name_list else self.category_name_list))
  File "H:\python\PornSpider-master\pornspider.py", line 165, in init_categories_p
    results.append(pool.apply_async(category,(name,)+category_params.get(name)))
TypeError: can only concatenate tuple (not "NoneType") to tuple
